py37:
    image: python:3.7
    stage: test
    script:
        - pip install -U pip
        - pip install -U virtualenv
        - pip install poetry
        - poetry install -E io -v
        - poetry run pytest tests
#    - apt-get update -q -y
#    - pip install -U pip
#    - pip install aiofiles
#    - pip install ruamel.yaml
#    - pip install toml
#    - pip install msgpack
#    - pip install -U pupy
#    - pip install pytest
#    - pip install pytest-cov
#    - pytest tests
