language: python
python:
    - "3.6"
    - "3.7"
    - "3.6-dev"  # 3.6 development branch
    - "3.7-dev"  # 3.7 development branch

before_install:
    - pip install -U pip
    - pip install -U virtualenv
    - pip install poetry
    - pip install pyparsing==2.4.0

install:
    #    - pip install -U aiofiles
    #    - pip install -U ruamel.yaml
    #    - pip install -U toml
    #    - pip install -U msgpack
    #    - pip install -U pupy
    #    - pip install -U pytest
    #    - pip install -U pytest-cov
    - poetry install -v

script:
    - poetry run pytest tests

