language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - pytest --doctest-modules
