language: python
python:
  - "3.6"
  - "3.7"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
before_install:
    - pip install -U pip
#    - pip install poetry
install:
    - pip install -e .
#  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
#  - export PATH=$PATH:~/.poetry/bin
#  - poetry install
    #- pip install -U pip
    #- pip install -e .

script:
    - pip install pytest
    - pip install pytest-cov
    - pytest tests
#    - poetry run pytest
