language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install cython
  - pip install tqdm
  - pip install .
# command to run tests
script: pytest