dist: xenial # required for Python >= 3.7 (the 38dev and nightly things)
language: python
cache: pip  # for caching pip deps

python:
    - "3.6"      # plain jane 3.6
    - "3.7"      # plain jane 3.7
    - "3.6-dev"  # 3.6 development branch
    - "3.7-dev"  # 3.7 development branch
    - "3.8-dev"  # 3.8 development branch
    - "nightly"  # nightly build
    - "pypy3"    # pypy
    - "pypy3.6"    # pypy

before_install:
    - pip install -U pip
    - pip install -U virtualenv
    - pip install poetry

install:
    - poetry install -E io -v --no-dev

script:
    - poetry run pytest tests
